# Generated by Django 3.2.19 on 2023-05-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_2',
        ),
    ]
